### ISSUE TITLE
Looks like the example part is not complete

### ISSUE THREAD

**Issue by madhavan020985** [channikhabra/fecha-locales#1]
I did `cd  fecha-locales/example` and ran, `npm install` and then ran, `webpack-dev-server --config ./webpack.cofig.js` (here the file must be renamed to webpack.config.js and not webpack.cofig.js)

It throws error as,
````
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'fecha-locales/locales/fr' in /home/sk/ws/fecha-locales/example/src
 @ ./src/index.js 12:10-45

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'fecha-locales/locales/es' in /home/sk/ws/fecha-locales/example/src
 @ ./src/index.js 13:10-45
````

**Comment by channikhabra** [comment]
Fixed via https://github.com/channikhabra/fecha-locales/commit/3829f1e13fd0bd5c748ab09f64f3c7af7364fa3c

**Comment by channikhabra** [comment]
@madhavan020985 Thanks for checking it out. I forgot to update the version number there.

**Comment by madhavan020985** [comment]
it works nwo
